### ISSUE TITLE
Limit text width to 60% of the center of the canvas

### ISSUE THREAD

**Issue by apoapostolov** [elizeuangelo/fvtt-module-narrator-tools#1]
On full screen, the text flows from one corner to the other making the readers move their heads and eye focus to read whole lines. This is tiresome and takes more time especially when on screens people tend to focus on one point. To improve the readability of longer narration, add margins on left and right so the text is focused on the center 60%-70% of the screen.

**Comment by elizeuangelo** [comment]
I could not replicate this issue. Could you tell me wich device/browser this is happening? Also, could this be related to any other module being active?

**Comment by apoapostolov** [comment]
Here's what I see when using Lorem Ipsum text:

![image](https://user-images.githubusercontent.com/4083812/91700830-1c83e000-eb7f-11ea-89b1-807d329d338d.png)

This is not bad, almost at 80% of the canvas width. My suggestion is to cut this to 66% where the reader would only need to read  down, rather than move his eyes left to right on each line. This will speed up reading within the alotted time (btw, you calculate time based on content right? If not, you should to avoid people not reading it fully)

**Comment by elizeuangelo** [comment]
Done, I tested several approachs but your solution seemed the best.
