### ISSUE TITLE
Setting to allow for unlimited length / button press to hide narration.

### ISSUE THREAD

**Issue by NoBullPleb** [elizeuangelo/fvtt-module-narrator-tools#10]
Essentially, I'd like to be able to set it so that the Narration Text lasts until I hit a button (such as enter) or maybe click the text to make it disappear.

**Comment by elizeuangelo** [comment]
Hm.. cool feature but I would make it an optional setting.

**Comment by NoBullPleb** [comment]
Of course! Default functionality is great for shorter messages, but I'd like to take the parts I plan on reading out loud and just click when I'm done reading. Bonus points if I can configure the button to press.

I'd be even cooler if I could have a journal entry with several Narrate macros, and just hit the right arrow key to display the next one (like a power point slide works).

**Comment by elizeuangelo** [comment]
Coming soon...

**Comment by elizeuangelo** [comment]
Added in v0.50 698ce81c66b8f747704872fa1b476485ec72c44c please test it

**Comment by elizeuangelo** [comment]
Added in v0.50 698ce81c66b8f747704872fa1b476485ec72c44c
