### ISSUE TITLE
Narrate not appearing on canvas

### ISSUE THREAD

**Issue by zarmstrong** [elizeuangelo/fvtt-module-narrator-tools#11]
Using pathfinder 2e game system, all modules except narrate are disabled. Narration only appears in the chat log.

**Comment by elizeuangelo** [comment]
Im testing it and it seems to work as of 
![image](https://user-images.githubusercontent.com/56921633/93212100-846a2700-f738-11ea-84c4-007f0636557d.png)

Could you tell me wich version of Foundry + Pf2e are you using?

**Comment by zarmstrong** [comment]
same version of foundry,
10.10.10.1973 for Pathfinder 2e

**Comment by zarmstrong** [comment]
When I do `/narrate this is narration` I only get the message in chat and the following in console: `Foundry VTT | Created ChatMessage with id PslBeqxdprmLsClG`  Should I be seeing more from the console to indicate the canvas message?

**Comment by elizeuangelo** [comment]
Please try updating your Pathfinder 2e module, it might be an issue with that specific version.

**Comment by zarmstrong** [comment]
I am on a newer version than you :)

**Comment by elizeuangelo** [comment]
Yeah its kinda odd... I had just updated before taking that picture. I have not updated now and its showing the same version as yours, but Narrator tools is working as normal.

![image](https://user-images.githubusercontent.com/56921633/93268501-a6d56200-f783-11ea-916f-7287471679a6.png)

It could be a corrupt installation somewhere. Try reinstalling the module and please let me know if it doesnt work (more people could be having this issue).

If you can, contact me in discord maybe we can address this faster there. Magus#9576

**Comment by zarmstrong** [comment]
After testing, it appears limited to my computer, as it doesn't work on both Chrome and Firefox. It works on Chrome on a second computer, so the issue is limited to my primary computer.  Will try to determine if there's something on my system that might be preventing it from appearing

**Comment by elizeuangelo** [comment]
Try updating Chrome to 85.0.4183.102 and see if it persists.

**Comment by zarmstrong** [comment]
All is working now.  Seems like something was up with my system, a reboot fixed it in both Chrome and Firefox
