### ISSUE TITLE
Journal macros not working

### ISSUE THREAD

**Issue by Pawper** [elizeuangelo/fvtt-module-narrator-tools#14]
First - I can use `/narrate` in chat fine:
![image](https://user-images.githubusercontent.com/22269691/93557931-205e8300-f931-11ea-9941-d038f77a6fe1.png)

I stored the chat command as a macro and added the macro to the journal entry:
![image](https://user-images.githubusercontent.com/22269691/93558010-5b60b680-f931-11ea-8ec5-0e9dcf7e51cc.png)

But when I click the `>_Narrate` button I get an error:
![image](https://user-images.githubusercontent.com/22269691/93558027-61569780-f931-11ea-89bf-3870380b8219.png)

**Comment by Pawper** [comment]
I figured it out! thanks

**Comment by sambomb** [comment]
> I figured it out! thanks

How do you fixed it? 
im having the same problem

**Comment by elizeuangelo** [comment]
> > I figured it out! thanks
> 
> How do you fixed it?
> im having the same problem

You need to import the macro from the compendium.

**Comment by sambomb** [comment]
![image](https://user-images.githubusercontent.com/244795/93601468-a6adb000-f997-11ea-9d60-6d37d2cc4c2b.png)
![image](https://user-images.githubusercontent.com/244795/93601524-b7f6bc80-f997-11ea-9bb6-6ce9eea93c31.png)
When i click, nothing happens

**Comment by sambomb** [comment]
It dont work from the compendium, just if you move it to the toolbar and add to the journal...

**Comment by elizeuangelo** [comment]
Hey there, I redesigned everythign from scratch, now you select the text you want to narrate, you right-click inside the journal and a menu opens.

Tell me if its better than the macros.
