### ISSUE TITLE
Narrate macro in journal entry does not include links in chat

### ISSUE THREAD

**Issue by Pawper** [elizeuangelo/fvtt-module-narrator-tools#15]
I have this journal entry:
![image](https://user-images.githubusercontent.com/22269691/93567221-2f4e3100-f943-11ea-9b98-7e8e0d29c7bc.png)

When I click the `>_Narrate` button:
![image](https://user-images.githubusercontent.com/22269691/93567288-44c35b00-f943-11ea-9e09-3a13d496064d.png)

The chat message does not display the `letter` button.
![image](https://user-images.githubusercontent.com/22269691/93567355-5d337580-f943-11ea-942d-eda4b347f7f4.png)

When I enter the `/narrate` command in chat, it does.
![image](https://user-images.githubusercontent.com/22269691/93567386-6b819180-f943-11ea-841a-2b89649aa9b5.png)

**Comment by elizeuangelo** [comment]
I changed to a right-click on the journal, there are no more macros. Now it also works on entities selected.
