### ISSUE TITLE
Macro question and minor enchantement (pause game)

### ISSUE THREAD

**Issue by SergioCaptio** [elizeuangelo/fvtt-module-narrator-tools#17]
Hi, first of all. No issue here. Great module.
I manange to understand that with `Narrator.createSpecialChatMessage('narrate', "text")` I can create macro that send text to the middle of the screen. _Is there a similar command to toggle the vignette effect?_ 

I really would love to see the option to have the vignette effect when the game is paused. Pausing the game is great to stop player wondering around during a description, but I also accidentally press space and I dont realize that the game is paused until someone told me. Having the vignette effect active would give an immediate feed back to me and all my player.
I belive I wouldn't be the only one to love this feature,

Again great job and great module 
PS: I love the journal integration

**Comment by elizeuangelo** [comment]
> Is there a similar command to toggle the vignette effect?

Added in last version command `Narrator.setScenery(status)` to control the vignette. Status can be true, false or undefined (the function works as a toggle then).

> I really would love to see the option to have the vignette effect when the game is paused.

Done, check the configurations.
