### ISSUE TITLE
Change colour of Text

### ISSUE THREAD

**Issue by Gegh** [elizeuangelo/fvtt-module-narrator-tools#19]
It would be greate if one could change the Font (Style, Colour,...) of this

![grafik](https://user-images.githubusercontent.com/5196891/97154919-d7da8680-1774-11eb-88b7-c2260dd2e0e3.png)

**Comment by elizeuangelo** [comment]
Color of text, text-shadow.. what else people want to stylize?

Please anyone add here more suggestions. I dont want to flood the configuration with irrelevant options but anything relevant CSS style-wise I will add.

**Comment by elizeuangelo** [comment]
I added, next update it will be released

**Comment by apoapostolov** [comment]
We're your able to find full CSS support? I want to be able to set a webfont

**Comment by Gegh** [comment]
> 
> 
> I added, next update it will be released

Thanks a lot! Any chance for a release before this weekend ? I have a game coming up on Friday and could really use this :)

**Comment by elizeuangelo** [comment]
> Thanks a lot! Any chance for a release before this weekend ? I have a game coming up on Friday and could really use this :)

Done, just access it from the modules configuration menu.
