### ISSUE TITLE
Settings allowing custom CSS

### ISSUE THREAD

**Issue by apoapostolov** [elizeuangelo/fvtt-module-narrator-tools#2]
Please add mod settings, where the DM only can set a CSS style opening the door for using custom fonts from Google Web Fonts or similar sources. This would also allow the user to fix #1 by himself by applying margins on left and right.

**Comment by elizeuangelo** [comment]
Probably next release I will have a solution for this.

**Comment by apoapostolov** [comment]
@elizeuangelo Thank you for your hard work. As for the background shade it is fairly good at the moment. What really is missing is font size and support for Google web fonts.

**Comment by elizeuangelo** [comment]
Done! In the module configuration you can load google fonts and change their size, overtime I will increment it.
