### ISSUE TITLE
New Style Options

### ISSUE THREAD

**Issue by elizeuangelo** [elizeuangelo/fvtt-module-narrator-tools#20]
Please post here your suggestions regarding new style configurations.

**List**
> Text-style
Color
Text-shadow

**Comment by apoapostolov** [comment]
Webfont from Google.
Honestly, I much prefer full CSS edit field than limited predefined fields
so maybe just add few presets and then a field for full CSS edit?

**Comment by elizeuangelo** [comment]
> Honestly, I much prefer full CSS edit field than limited predefined fields

I havent thought about that, good idea.

> Webfont from Google.

There is already support for that?

**Comment by apoapostolov** [comment]
Not yet afaik.

**Comment by elizeuangelo** [comment]
In the configuration menu there is a Google Font option to load fonts from Google Web Fonts. Access the configuration menu from the module settings.

**Comment by elizeuangelo** [comment]
> Honestly, I much prefer full CSS edit field than limited predefined fields

Done, just use the CSS config in the configuration menu.

**Comment by apoapostolov** [comment]
This can be closed as CSS and webfonts are now exposed.
