### ISSUE TITLE
Clash with DnD5e UI

### ISSUE THREAD

**Issue by amcvfx** [elizeuangelo/fvtt-module-narrator-tools#22]
I'm currently using the DnD5e UI module and there is currently a clash with the text display in chat for narrated and described text. It displays a shadow under text which conflicts visually. Could an option be added to turn the shadow off on the chat window text?

![image](https://user-images.githubusercontent.com/35099081/100594797-0c041280-32f2-11eb-9e36-8ecd0630b9ca.png)

**Comment by elizeuangelo** [comment]
Corrected it in latest release a188664afb9282778f05cd5f4542047e6d7d0f03
