### ISSUE TITLE
 /desc and /narrate in combination with rolls

### ISSUE THREAD

**Issue by Nedrapter** [elizeuangelo/fvtt-module-narrator-tools#25]
I had the following macro:
/desc You hear rolling behind the GM screen [[/gmr 1d20]]
which was displaying this message to the players [https://cdn.discordapp.com/attachments/782416080827318293/786573763268968458/Capture.PNG](url)
and clicking the 1d20 icon, would roll the die (depending on your setting it would be visible or not to players).
In the last updates, this is not working anymore. The message is displayed, but no die is rolled when I click on it.

**Comment by elizeuangelo** [comment]
Corrected it in latest release a188664afb9282778f05cd5f4542047e6d7d0f03
