### ISSUE TITLE
appearance in /stream page

### ISSUE THREAD

**Issue by MaronKB** [elizeuangelo/fvtt-module-narrator-tools#27]
I often use a method that makes /stream pages pdf to preserve chat logs.
However, on the /stream page, I found that chat using /desc or /narrate was completely the same as other chats.
It was not white letter on a dark background like the original log theme, but black letter on a bright background like any other chats, and even had a name space.
When I checked the html of the /stream page, I found that the id, class, and style of the narrator tools were missing.
Could you let the styling of the narrator tools be applied on the /stream page?

**Comment by elizeuangelo** [comment]
Sure I will work on that. Im kinda busy with other projects but as soon as I can will fix it, ty

**Comment by elizeuangelo** [comment]
Corrected it in latest release a188664afb9282778f05cd5f4542047e6d7d0f03
