### ISSUE TITLE
Voice Narration Support with a new /scene command

### ISSUE THREAD

**Issue by apoapostolov** [elizeuangelo/fvtt-module-narrator-tools#3]
This was discussed between us on Discord but wanted to write it down for reference.

A new command called /scene would trigger dimming of the canvas and apply vignette effect to the corners of the canvas. This mode can be used by the DM to start a "cutscene description" and cue players to listen rather than jump to act. Also, it can be used to set the scene darker for the /narrate commands to follow.

Typing /scene during a scene ends the scene removing the dimming and the vignettes.

**Comment by elizeuangelo** [comment]
I added a tool on the Token Toolbox, on the left size of the canvas. Its better than a chat command.

**Comment by apoapostolov** [comment]
It is very beautiful. I noticed an issue that you draw on canvas but not under the sidebar, resulting in this view when the sidebar is minimized. 

![image](https://user-images.githubusercontent.com/4083812/91766926-03614a80-ebe4-11ea-8b19-6aa612a4f294.png)

**Comment by apoapostolov** [comment]
Here's example how it looks with restored sidebar: You can see it is brighter on the side of the canvas, under the sidebar. 

![image](https://user-images.githubusercontent.com/4083812/91768133-dd3caa00-ebe5-11ea-83d8-b586f7588cac.png)
