### ISSUE TITLE
Scrolling text stopped appearing (console errors)

### ISSUE THREAD

**Issue by r-valyar** [elizeuangelo/fvtt-module-narrator-tools#31]
The on-scene scrolling text stopped appearing. The console shows the errors below after I click "narrate". The chat message is fine.
I have tried to put values in message settings such as font size for no result, the the other is unclear. 
```
Invalid property height set to 0 Missing plugin? gsap.registerPlugin() gsap-core.js:84:18
Invalid property opacity set to 0 Missing plugin? gsap.registerPlugin() gsap-core.js:84:18
```

**Comment by elizeuangelo** [comment]
I cant reproduce the error, what foundry's and system's versions are you using?

It always happens or it happens only on a certain routine?

Could you try creating an empty world and loading only the module? Possibly reinstall it before doing so

**Comment by r-valyar** [comment]
Re-installing the module fixed it. In general the issue was in new/existing worlds.
