### ISSUE TITLE
Dimming the canvas only dims it for the GM and not the players

### ISSUE THREAD

**Issue by SuicidalBomb** [elizeuangelo/fvtt-module-narrator-tools#35]
I have had multiple players screenshare and none of them have the screen dim when i click the button.

**Comment by elizeuangelo** [comment]
Sorry! I removed socket in the module.json because im working on a new version where we dont use sockets. Accidentally I updated the module.json from the new version when I shouldnt.

It should work now please test it.

**Comment by SuicidalBomb** [comment]
It works! Thank you so much
