### ISSUE TITLE
/desc and /narrate do nothing

### ISSUE THREAD

**Issue by EsotericOdyssey** [elizeuangelo/fvtt-module-narrator-tools#36]
Foundry 0.7.9, Simple Worldbuilding 0.4, hosted on Forge

**Comment by EsotericOdyssey** [comment]
update: it seems to be a conflict with Moerill's Expandable Markdown Editor

**Comment by elizeuangelo** [comment]
I just tested and couldnt replicate. Im using `Moerill's Expandable Markdown Editor` in `Simple Worldbuilding 0.4` and it worked fine.

**Comment by EsotericOdyssey** [comment]
> I just tested and couldnt replicate. Im using `Moerill's Expandable Markdown Editor` in `Simple Worldbuilding 0.4` and it worked fine.

I managed to fix it on my end. Did you have markdown enabled for chat or disabled? I had it enabled initially but disabling it fixed the problem.

**Comment by elizeuangelo** [comment]
Yes, I have it enabled. But nevertheless the `/narrate` command ignores the markdown

**Comment by EsotericOdyssey** [comment]
not sure why that specifically was causing a problem for me, then.
