### ISSUE TITLE
Allow Narrate/Describe from Items/Actors/Other places.

### ISSUE THREAD

**Issue by SabreRunner** [elizeuangelo/fvtt-module-narrator-tools#39]
I would like the ability to select and right-click Narrator on other things besides the Journal.

**Comment by elizeuangelo** [comment]
As of v0.55 all `div.editor-content` now allow the use of the context menu.

This means it will work on journals, items descriptions, several places inside an actor sheet, etc.
It doesnt work on anything wich is not an `editor-content`.

commit 4b23c567bbdbdf2f9df69d1469a571378c5a04ed
