### ISSUE TITLE
Issues with vignette not covering the surface under the sidebar.

### ISSUE THREAD

**Issue by apoapostolov** [elizeuangelo/fvtt-module-narrator-tools#4]
I posted this in #2 but I will open a new issue so that it remains open.

The vignette effect needs to hard-dim the surface under the sidebar otherwise it appears brighter even through the sidebar dark glass transparency, and completely bright if the sidebar is minimized.

![image](https://user-images.githubusercontent.com/4083812/91776630-6c51be00-ebf6-11ea-9c8c-5db4b6867c02.png)

![image](https://user-images.githubusercontent.com/4083812/91776622-6825a080-ebf6-11ea-9d18-3279520632fe.png)

**Comment by elizeuangelo** [comment]
I believe I fixed it in the v0.15.

**Comment by apoapostolov** [comment]
@elizeuangelo I don't want to be too picky so feel free to leave it like that, but it would have been a better approach to not extend the vignette to the screen space but keep it as it were, and then add as dim mask under the field of the sidebar.
