### ISSUE TITLE
Compatibility with WFRP4 ruleset

### ISSUE THREAD

**Issue by Ceodryn** [elizeuangelo/fvtt-module-narrator-tools#40]
When /narrate using in the WFRP4 ruleset, the text display fine in the center screen, but the first two letters are cut in the chat. It would be great to find a work-around.

![Screenshot 2021-04-23 163320](https://user-images.githubusercontent.com/7441270/115886904-af94c180-a451-11eb-95f5-c10e7be66d7a.png)

https://github.com/moo-man/WFRP4e-FoundryVTT

**Comment by elizeuangelo** [comment]
Done b5f01a545f64812ee199645323a99aa277937178

**Comment by elizeuangelo** [comment]
Im increasing compatibility with WFRP4 further on next release... removing those border headers
