### ISSUE TITLE
Doesn't play well with Polyglot

### ISSUE THREAD

**Issue by simulacrum-1** [elizeuangelo/fvtt-module-narrator-tools#41]
If using 'Polyglot' module narrations appear in the first (alphabetical) language in your world. Rather than no language at all.

**Comment by elizeuangelo** [comment]
Its because some people requested it should work with polyglot (though its not 100% integrated yet, /narrate needs work) to display text on descriptions. If using the 'common' language the text is displayed normally.

How do you think it should work? Whats a better behavior?

**Comment by simulacrum-1** [comment]
I would say it's a bit spammy if it always displays in the language.
It would be nice to have the choice to either do:
1. An Out-of-character describe/narrate. Which doesn't use Polyglot.
2. Or a In-Character describe/narrate where as the GM you can choose from the dropdown any language I would say.

Ps. It was my mistake why it appeared not as the default language. As the GM i'd edited my player configuration.

**Comment by simulacrum-1** [comment]
Like this \/
![Screenshot 2021-04-26 at 17 57 00](https://user-images.githubusercontent.com/68729767/116123445-e7eb0880-a6ba-11eb-9f6e-07319a32e5de.jpg)

**Comment by elizeuangelo** [comment]
I added a new message-type configuration so everyone can have their way, please check if this is better
627f6ed23814b87365637440c54becf39780cd1a
