### ISSUE TITLE
Error leaves narrated text stuck on players screen

### ISSUE THREAD

**Issue by amcvfx** [elizeuangelo/fvtt-module-narrator-tools#42]
![image](https://user-images.githubusercontent.com/35099081/116625245-3a3d5b00-a941-11eb-99a6-fb5fc67f65b3.png)

I'm getting this error when narrating text. The text stays stuck on the players screen, and the text doesn't appear for the DM, nor does it show the Pause and Close buttons. I've been trying to find the clashing module as when I use Find the Culprit I don't always get the error but it keeps on resulting in a module that isn't causing an error. I'm wondering if there are a combination of modules clashing?

**Comment by GabrielDeschain** [comment]
I'm also having the same error!

**Comment by elizeuangelo** [comment]
Whats your Foundry and module's version?

Also:
1. Restarting foundry fix the issue?
2. Can you check disabling all modules but narrator-tools?
3. The behavior seems random or it is easy for you to reproduce?

**Comment by amcvfx** [comment]
1. The error still occurs after restarting Foundry and my forge server.
2. Narrator Tools works correctly when it's the only module running.
3. I haven't been able to find the clashing module with Find the Culprit as it always returns a different module and it's never the right one. So maybe it's more than one module clashing? I don't really have time to check them side by side with my 100+ modules.
4. The scenery tool seems to work fine and I can see it in the sidebar. I could have a few modules that could change map tools? I'm not sure which ones they are though.

**Comment by elizeuangelo** [comment]
I commited an attempt on addressing this issue but because I cant reproduce it, Im gonna need you guys to test it

627f6ed23814b87365637440c54becf39780cd1a

**Comment by amcvfx** [comment]
It seems to have fixed the issue. Thanks!
