### ISSUE TITLE
Move the "Scenery" button to the main column

### ISSUE THREAD

**Issue by r-valyar** [elizeuangelo/fvtt-module-narrator-tools#45]
The location of the Scenery button is in the Token sub-menu, while it makes sense to be available to GM as part of the main menu, as not every scene is actually combat with tokens and etc. 

This proposal is based on feedback from several GMs that used Foundry in co-GM configuration.

![image](https://user-images.githubusercontent.com/63558984/122346546-c0454d80-cf51-11eb-98ae-0acc981980d3.png)

**Comment by elizeuangelo** [comment]
Done in commit 1a025ce8666fcf04b1ce9aabbb9c1b9f7937a3d0
