### ISSUE TITLE
/desc can't make separate paragraphs by starting new lines

### ISSUE THREAD

**Issue by danzchen7** [elizeuangelo/fvtt-module-narrator-tools#46]
Whenever I start a new line of text, I'd expect it to show that line as a separate paragraph after I post it. It does not do this.

CGMP module does this for the /desc command, so I wish Narrator Tools could too.

**Comment by elizeuangelo** [comment]
Corrected in commit 689a9bea1689b51007b01415ea257669bcc56fbd
