### ISSUE TITLE
Issue with updated Manifest URL and update to same version

### ISSUE THREAD

**Issue by r-valyar** [elizeuangelo/fvtt-module-narrator-tools#48]
The issue is again appearing - every check for update there is update to same version after message with manifest location change.
![image](https://user-images.githubusercontent.com/63558984/124887474-dfc61800-dfdd-11eb-9bb3-32e9b674600b.png)

**Comment by elizeuangelo** [comment]
I see, can you check if this stopped?

**Comment by r-valyar** [comment]
Seems fixed!
