### ISSUE TITLE
Player QoL - Copy to Clipboard button on Narration

### ISSUE THREAD

**Issue by apoapostolov** [elizeuangelo/fvtt-module-narrator-tools#49]
Often, when the GM uses the narration to drop a puzzle piece as a reading or an important message, or players just want to comb the text later for clues, they have to copy the text. Usually what they do is quickly print the screen and then write it down. They have to ask to be played again, or ask to be copied in chat without the fancy effect. This turns a great moment into a nuisance.

It would make absolute sense to help players who want to quickly take a note. A Copy to Clipboard button would allow them to copy the text immediately and then be able to use it as they see fit. 

A cruel GM may have the right to disable this button, in Settings.

**Comment by Constnt1** [comment]
You can just copy and paste from the chat window. Is there an option to remove the copy button? I find it breaks immersion.

**Comment by elizeuangelo** [comment]
10baa8201930931eba6f1fa7e1689f413e534c80

Now everyone is happy!

The copy button is now an optional configuration `default: false`
