### ISSUE TITLE
Calculate and spread the background to the number of lines the text uses based on number of characters in the message

### ISSUE THREAD

**Issue by apoapostolov** [elizeuangelo/fvtt-module-narrator-tools#5]
I always test with Lorem Ipsum texts and this allowed me to see that the dark mask behind the text does not calculate its height based on the number of lines in the text.  Possibly the lost below will help you?

https://stackoverflow.com/questions/783899/how-can-i-count-text-lines-inside-an-dom-element-can-i/42461755

![image](https://user-images.githubusercontent.com/4083812/91780818-4e3d8b00-ec01-11ea-9745-cbb528fe6951.png)

**Comment by elizeuangelo** [comment]
It calculates its height based on the number of lines, but it has a constant 45px top-bottom-margin (=90) so in big texts that additional margin may seem small and its already on the low-gradient side... on my screen I can easily spot it and it seems fine but Idk, if you are having trouble seeing it I might increase the height on a % basis instead of fixed.

**Comment by apoapostolov** [comment]
I can clearly see that the background covers about 5 lines, but you have 7 lines before you start scrolling, so increasing to cover max 7 lines would solve this minor issue.

**Comment by elizeuangelo** [comment]
I increased the height by a % of the box line size instead of fixed rate added to that size, I believe this issue got covered, please let me know if you are still having issues.

**Comment by apoapostolov** [comment]
Sorry there seems not to be much difference. Here's how it looks now:

![image](https://user-images.githubusercontent.com/4083812/91855287-a611db80-ec6d-11ea-954d-3e68d4fa467a.png)

You can test yourself to get it right, here's the text I use to test

"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."

**Comment by apoapostolov** [comment]
As of 0.2.1 the stronger dimming seems to remove much of the need to widen the mask.

**Comment by elizeuangelo** [comment]
Im still thinking the best way to approach this, its just that its too dependant on the screen size. The frame always has considered the number of lines its just the balance between dimming and gradient is  too delicate.

The easy approach would just make height also variable on screen size, but im not feeling confident about this.
