### ISSUE TITLE
[bug] macros are not working

### ISSUE THREAD

**Issue by brunocalado** [elizeuangelo/fvtt-module-narrator-tools#51]
Hi 

I can't get macros to work

tks

**Comment by elizeuangelo** [comment]
The developer wiki is outdated, Im going to update it but if you could elaborate what you are trying to do I can help you better

**Comment by brunocalado** [comment]
I want to trigger narrate animation with a macro.

Lot's of uses: modules like forien's tiles etc

**Comment by elizeuangelo** [comment]
The NarratorTools object in window has all the funcionalities of the module.

Send simple narration:
`window.NarratorTools.chatMessage.narrate("Awesome message!")`

Concatenate several narrations together:
`window.NarratorTools.chatMessage.narrate(["Awesome message!","Awesomer still!!"])`

Open/close the scenery:
`window.NarratorTools.scenery(true | false)`

Hooks:
`narration` - when a narration is opened..
`narration_closes` - when a narration closes...

**Comment by brunocalado** [comment]
tks
