### ISSUE TITLE
[Request] Macro for Scenery Tool

### ISSUE THREAD

**Issue by weepingminotaur** [elizeuangelo/fvtt-module-narrator-tools#57]
It would be really useful if one could toggle the scenery tool (dim canvas, vignette) via macro. Would open up the action to be triggered by other modules.

**Comment by elizeuangelo** [comment]
There already is!

```NarratorTools.scenery(TRUE | FALSE)```

**Comment by weepingminotaur** [comment]
Had no idea. Thank you!

**Comment by weepingminotaur** [comment]
I am not able to get this macro to work. Returns console errors every time.

**Comment by elizeuangelo** [comment]
Weird, its working fine in my setup. Could you post a screenshot of the error you are getting?

**Comment by weepingminotaur** [comment]
This is the console error I get when I paste the line you provided into a macro and try to run the macro.
<img width="686" alt="Screen Shot 2022-06-13 at 1 23 55 PM" src="https://user-images.githubusercontent.com/90105219/173410319-58b9dfe8-46e8-4bff-aa16-6779ad78cd52.png">

**Comment by elizeuangelo** [comment]
I used caps fo TRUE or FALSE because I wanted to make it clear that was a boolean variable, in javascript boolean variables are lower-capitalized: `true` or `false`.

**Comment by weepingminotaur** [comment]
Ok, with lower-case true and false, it turns on scenery, but running the macro again doesn't turn it off.

**Comment by weepingminotaur** [comment]
Seems like I need one macro for one, one macro for off?

**Comment by elizeuangelo** [comment]
Try the macro without passing any parameter, if you want it to toggle. ```NarratorTools.scenery()```
