### ISSUE TITLE
Use scene-control instead of control-tool for better integration with Minimal UI

### ISSUE THREAD

**Issue by weihanderz** [elizeuangelo/fvtt-module-narrator-tools#58]
Change on line 129:
`const btn = $('.control-tool[data-tool=scenery]');`
to
`const btn = $('.scene-control[data-tool=scenery]');`

and line 228:
``const btn = $(`<li class="control-tool toggle ${active ? 'active' : ''}" title="${title}" data-tool="${name}"><i class="${icon}"></i></li>`);``
to
``const btn = $(`<li class="scene-control toggle ${active ? 'active' : ''}" title="${title}" data-tool="${name}"><i class="${icon}"></i></li>`);``

**Comment by elizeuangelo** [comment]
Fixed in release v0.72.
