### ISSUE TITLE
[Feature Request] Tag option to increase size of certain parts of the narration.

### ISSUE THREAD

**Issue by DarknesSeeker** [elizeuangelo/fvtt-module-narrator-tools#60]
Been having a lot of fun with this module, but I'm missing the possibility of mixing text sizes for the narration tool. For example, If in a journal I have:

```
"<h1>BOSS NAME</h1><br>
The So-Called-Boss of the Dungeon"
```

When narrated, the description in chat picks up correctly the headline tag, but the narration puts the entire string in the same size.
Is there any way to specify or change the size for specific parts of the string for the narration tool, even if using the macro tools such as chatMessage.Narrate?

**Comment by elizeuangelo** [comment]
Hm, it works like that because mostly often, when people narrate through the journal's context menu they dont want the journals HTML code passing to the narration. But I will give more thoughts into this, maybe we should always consider passing the HTML tags?

**Comment by elizeuangelo** [comment]
I actual like this... if I allow HTML it would even work using polyglots weird languages. I will make it in next release, ty.
