### ISSUE TITLE
Issue with CSS in the toolbar

### ISSUE THREAD

**Issue by apoapostolov** [elizeuangelo/fvtt-module-narrator-tools#64]
The mod seems to set few more CSS classes than it should in the toolbar parent, and that causes it to look out of place compared to all other buttons

``<li class="scene-control control-tool toggle" title="Scenery" data-tool="scenery"><i class="fas fa-theater-masks"></i></li>``

should instead show as

``<li class="scene-control" title="Scenery" data-tool="scenery"><i class="fas fa-theater-masks"></i></li>``

**Comment by elizeuangelo** [comment]
I tested this and I could not replicate the issue, probably its due to a stylization module of some sort.

But because it wouldnt affect the module and in core it doesnt have any effect on the style I removed the control-tool class as requested.
