### ISSUE TITLE
Request: v10 compatibility

### ISSUE THREAD

**Issue by weepingminotaur** [elizeuangelo/fvtt-module-narrator-tools#65]
Is there an estimated date for Narrator Tools supporting v10?

**Comment by elizeuangelo** [comment]
Honestly I didnt updated the manifest yet but I believe the module already is compatible with v10.

**Comment by weepingminotaur** [comment]
> Honestly I didnt updated the manifest yet but I believe the module already is compatible with v10. Have you noticed any bugs or issues?

Good to know! It listed as white in Module Compatibility Checker, so I wasn't sure what the status was.

**Comment by ThingsCouldGetDicey** [comment]
i cant install this.

**Comment by elizeuangelo** [comment]
I just released a version with v10 manifest, please tell me if installation is successfull.

**Comment by Fyrexian** [comment]
there is a bug where the right clicking a journal entry to show the narrate button doesn't appear

**Comment by elizeuangelo** [comment]
Fixed in v0.76
