### ISSUE TITLE
Send the command from Journal

### ISSUE THREAD

**Issue by brunocalado** [elizeuangelo/fvtt-module-narrator-tools#7]
Hi.

Can you make the commands work from the journal?

![image](https://user-images.githubusercontent.com/4999783/92490141-07363380-f1c7-11ea-8c43-d88298717980.png)

**Comment by elizeuangelo** [comment]
You can make macros and use them in the journal.

![image](https://user-images.githubusercontent.com/56921633/92499689-8ed56f80-f1d2-11ea-8f60-089062cb85a4.png)
![image](https://user-images.githubusercontent.com/56921633/92499845-bcbab400-f1d2-11ea-9db6-b024be9574d6.png)
![image](https://user-images.githubusercontent.com/56921633/92499886-c93f0c80-f1d2-11ea-8415-5103a8efefc6.png)

**Comment by brunocalado** [comment]
There is a problem with this.

Imagine a campaign. Will create dozens of macros?

If you could just add the text in the journal it will be much easier.

**Comment by elizeuangelo** [comment]
You could have a macro that do the trick, one macro for all texts in journal. You select the text and it turns into a clickable.

I will look into it when I have some time so its part of the project

**Comment by elizeuangelo** [comment]
Added on latest release macros for chat.

![image](https://user-images.githubusercontent.com/56921633/93004816-26172b80-f521-11ea-9532-a056fb170f6e.png)

![image](https://user-images.githubusercontent.com/56921633/93004852-78f0e300-f521-11ea-8922-5bbf86370482.png)

**Comment by zarmstrong** [comment]
This feature doesn't seem to be working:

 ```
event.srcElement.closest is not a function
    at Macro.eval (eval at callScriptMacroFunction (Macros.js:176), <anonymous>:10:35)
    at Macro.callScriptMacroFunction [as callScriptFunction] (Macros.js:179)
    at Macro.renderMacro [as renderContent] (Macros.js:197)
    at Macro.executeMacro (Macros.js:221)
    at HTMLAnchorElement._onClickEntityLink (foundry.js:14429) "Macro Narrate: failed to catch narration."
```


journal content is:
```
@Compendium[narrator-tools.narrator-macros.I3ztJttPpvtN96iL]{Describe} This is a test description

@Compendium[narrator-tools.narrator-macros.qSMtVloC2rqjrfkL]{Narrate} This is a test narration
```

**Comment by zarmstrong** [comment]
Figured it out - have to import the macro, so it's a reference to the macro, not the compendium.
