### ISSUE TITLE
Add option to send Narration / Description as Message Type 2 (In Character)

### ISSUE THREAD

**Issue by cswendrowski** [elizeuangelo/fvtt-module-narrator-tools#8]
A user of Tabbed Chat would like the ability to do general narration, which Narrator Tools does excellently. However, Narrator Tools doesn't currently seem to set a Message Type, and therefore defaults to 0 (Other). An option to send as Type 2 (In Character) would allow the Narration messages to show up in the Tab the user desires.

https://github.com/cswendrowski/FoundryVTT-Tabbed-Chatlog/issues/13

**Comment by elizeuangelo** [comment]
On latest release I added an attribute called `msgtype` to the Narrator object. On setup it sets the value to `0` but you can change it to `2` or any other value as required.

A simple command to check if the Narrator object exists and change it:
`if (window.Narrator !== undefined) {
       Narrator.msgtype = 2;
}`

This way any module can change it as required.
